### ISSUE TITLE
Branching Issue

### ISSUE THREAD

**Issue by WWH987** [Ishi01/SoilConditionMapping#24]
Due to the branching issues on my end, can I ask everybody to **PR the current `dev` branch to your branches (if you are building on the previous `dev` branch)**. Otherwise, every new incoming PR will still cause the same issue again

**Comment by WWH987** [comment]
once done or do not need any change, please leave a message

**Comment by LongQin0121** [comment]
Have you solved the problem?

**Comment by LongQin0121** [comment]
Agree,  absolutly right~
