### ISSUE TITLE
Auto the all  process.

### ISSUE THREAD

**Issue by LongQin0121** [Ishi01/SoilConditionMapping#37]
Now in the UI part, as the User input the tx0 file, it would convert to txt.  Then user need choose the new created txt for Inversion.

I just wondering if we could auto this process without selecting the file for a second time?

**Comment by WWH987** [comment]
Can be done but I think it's unnecessary, since the user might want to work with the selected raw files, and the inversion is a quiet long process, so it requires threading to automate the process, which could lead to some unknown bugs.
